In [1]:
# Demonstrate basic functionality for Pauli Strings and Operators

import numpy as np
import matplotlib.pyplot as plt
import pauli_string_functions as pauli_func

In [2]:
# System Size
L = 5

In [3]:
# single strings are represented by numpy arrays with 1 byte integers (np.int8) of lenght L
# the integers encode the Pauli operators on the site 1, X, Y, Z <=> 0, 1, 2, 3

# here we create strings filled with the same operators
id_string = np.zeros(L, dtype=np.int8)
x_string = np.ones(L, dtype=np.int8)
y_string = np.full(L, 2, dtype=np.int8)
z_string = np.full(L, 3, dtype=np.int8)

print(id_string)
print(x_string)
print(y_string)
print(z_string)

[0 0 0 0 0]
[1 1 1 1 1]
[2 2 2 2 2]
[3 3 3 3 3]


In [4]:
# the strings weighted by complex sclars can be multiplied or commuted with each other,
# which returns the correct labels and coefficient of the product

# here we multiply and commute the x and y strings (each weighted by a factor 1.0) with each other
print(pauli_func.multiply_pauli_strings(x_string, y_string, 1.0, 1.0))
print(pauli_func.commute_pauli_strings(x_string, y_string, 1.0, 1.0))

# and now we exchage the strings to check that the operations are not-commutative
print(pauli_func.multiply_pauli_strings(y_string, x_string, 1.0, 1.0))
print(pauli_func.commute_pauli_strings(y_string, x_string, 1.0, 1.0))

(array([3, 3, 3, 3, 3], dtype=int8), 1j)
(array([3, 3, 3, 3, 3], dtype=int8), 2j)
(array([3, 3, 3, 3, 3], dtype=int8), (-0-1j))
(array([3, 3, 3, 3, 3], dtype=int8), (-0-2j))


In [ ]:
# Operators are sums of Paulis Strings with complex coefficients (real coefficients for hermitian operators but we only implement the general case)
